RegisterKeyMapping('nui', 'opens captcha', 'keyboard', 'E')
RegisterKeyMapping('takeweed', 'Add weed to inventory', 'keyboard', 'E')
RegisterKeyMapping('dropoffweed', 'Deliver weed at drop off point', 'keyboard', 'E')
RegisterKeyMapping('startmission', 'start mission', 'keyboard', 'E')
RegisterKeyMapping('returntempesta', 'Returns vehicle and gives money back', 'keyboard', 'E')
